### ISSUE TITLE
Release build for 1.19.0 missing?

### ISSUE THREAD

**Issue by Wyrrrd** [Auros/ImageFactory#7]
In case your continuous build is failing without you noticing, there is no release of the 1.19.0 version available yet.

In case you are simply not done, nevermind, I'll show myself out :)

**Comment by Auros** [comment]
This repository doesn't have CI, but ImageFactory has been ready for a while. I've been busy and a bit lazy so I haven't gotten around to releasing it yet. I'll do it in the next day or so.
